version: 2
jobs:
  build:
    docker:
      - image: java:openjdk-8-jdk
    working_directory: /app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}
            - v1-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}
            - v1-{{ .Branch }}
            - v1-develop
            - v1-master
      - run:
          name: Show version
          command: ./gradlew -v
      - run:
          name: Run tests
          command: ./gradlew check

      - store_artifacts:
          name: Store artifacts
          path: build
          destination: build
      - store_test_results:
          path: build/test-results/

      - deploy:
          name: Deploy bintray
          command: ./gradlew assemble bintrayUpload
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle"
            - "~/.m2"
